---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hdy2k
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: docker pull ghcr.io/ublue-os/mate
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://copr.fedorainfracloud.org/coprs/hazel-bunny/ricing/repo/fedora-42/hazel-bunny-ricing-fedora-42.repo
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
        - alacritty
        - kora-icon-theme
        - https://kojipkgs.fedoraproject.org//packages/libXScrnSaver/1.2.4/5.fc42/x86_64/libXScrnSaver-1.2.4-5.fc42.x86_64.rpm
        - fastfetch
        - adwaita-fonts-all
        - docker
        - docker-compose
        - tailscale
        - ddcutil
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
          title: Flathub
        install: # system flatpaks we want all users to have and not remove
           - org.gnome.Loupe
           - org.pulseaudio.pavucontrol
           - io.mpv.Mpv
           - io.github.pwr_solaar.solaar
           - app.zen_browser.zen
      - scope: user # Also add Flathub user repo, but no user packages
    
  - type: bling
    install:
      - rpmfusion

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
